live_config_reload = true

window.padding.x = 18
window.padding.y = 16
window.opacity = 0.90
window.blur = true
window.dynamic_padding = false
window.decorations = 'buttonless'


font.normal.family = 'SFMono Nerd Font'
font.normal.style = 'Regular'
font.size = 13
